version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building frontend...
      - npm run build

  post_build:
    commands:
      - echo Syncing to S3...
      - aws s3 sync build/ s3://$FRONTEND_BUCKET/ --delete
      - echo Invalidating CloudFront...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  type: NO_ARTIFACTS